FROM python:3.13-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y --no-install-recommends nmap arp-scan iputils-ping snmp && rm -rf /var/lib/apt/lists/*
RUN groupadd -r netscope && useradd -r -g netscope netscope
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app app
CMD ["celery","-A","app.workers.tasks.celery","worker","-Q","scanner","--loglevel=INFO"]
