route:
  receiver: ntfy
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: ntfy
    webhook_configs:
      - url: http://ntfy/netscope-alerts
        send_resolved: true
