import {useEffect,useState} from 'react';
import {Activity,AlertTriangle,Clock,HelpCircle,Monitor,Radio,Server} from 'lucide-react';
import {Bar,BarChart,Cell,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {api,downloadAssets} from '../lib/api';import {Layout} from '../components/Layout';
const colors=['#408cff','#35c979','#f1ad38','#a879e8','#ef6253','#5d7ca8'];
const go=(params:Record<string,string|number>)=>{location.hash='#/assets?'+new URLSearchParams(Object.entries(params).map(([k,v])=>[k,String(v)])).toString()};
export function Dashboard(){const [d,setD]=useState<any>();useEffect(()=>{api('/dashboard').then(setD)},[]);if(!d)return <Layout title="Tableau de bord"><div className="loading">Chargement…</div></Layout>;
 const cards=[['Actifs totaux',d.total,Server,'blue',{}],['En ligne',d.online,Activity,'green',{status:'online'}],['Hors ligne',d.offline,Monitor,'red',{status:'offline'}],['Nouveaux actifs',d.new_24h,Radio,'purple',{recent_hours:24}],['Inconnus',d.unknown,HelpCircle,'yellow',{status:'unknown'}]];
 return <Layout title="Tableau de bord"><div className="toolbar"><button>Dernières 24 heures</button><button className="button" onClick={downloadAssets}>Exporter</button></div>
 <div className="metrics">{cards.map(([l,v,I,c,filter]:any)=><article className="metric clickable" onClick={()=>go(filter)} title={'Afficher : '+l}><div><span>{l}</span><strong>{v.toLocaleString('fr-FR')}</strong><small>Cliquer pour ouvrir l’inventaire</small></div><i className={c}><I/></i></article>)}</div>
 <div className="charts"><Panel title="Actifs par type d’équipement"><ResponsiveContainer width="100%" height={250}><PieChart><Pie className="chartClick" data={d.by_type} dataKey="value" nameKey="label" innerRadius={65} outerRadius={100} onClick={(x:any)=>go({device_type:x.label})}>{d.by_type.map((_:any,i:number)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend onClick={(x:any)=>go({device_type:x.value})} layout="vertical" verticalAlign="middle" align="right"/></PieChart></ResponsiveContainer></Panel>
 <Panel title="Actifs par constructeur"><ResponsiveContainer width="100%" height={250}><BarChart data={d.by_vendor} layout="vertical" onClick={(x:any)=>x?.activePayload?.[0]&&go({manufacturer:x.activePayload[0].payload.label})}><XAxis type="number" hide/><YAxis type="category" dataKey="label" width={90}/><Tooltip/><Bar className="chartClick" dataKey="value" fill="#467ec9" radius={3}/></BarChart></ResponsiveContainer></Panel>
 <Panel title="Actifs par système d’exploitation"><ResponsiveContainer width="100%" height={250}><BarChart data={d.by_os} layout="vertical" onClick={(x:any)=>x?.activePayload?.[0]&&go({operating_system:x.activePayload[0].payload.label})}><XAxis type="number" hide/><YAxis type="category" dataKey="label" width={100}/><Tooltip/><Bar className="chartClick" dataKey="value" fill="#365f91" radius={3}/></BarChart></ResponsiveContainer></Panel></div>
 <div className="lower"><Panel title="Derniers scans"><div className="scanList">{d.recent_scans.length?d.recent_scans.map((s:any)=><div className="clickable" onClick={()=>location.hash='#/scans'}><Clock/><span><b>{s.target}</b><small>{new Date(s.created_at).toLocaleString('fr')}</small></span><em className={'badge '+s.status}>{s.status}</em></div>):<Empty text="Aucun scan lancé"/>}</div></Panel><Panel title="Dernières alertes"><Empty icon={<AlertTriangle/>} text="Aucune alerte récente"/></Panel></div></Layout>}
function Panel({title,children}:{title:string;children:any}){return <article className="panel"><h3>{title}</h3>{children}</article>}function Empty({text,icon}:{text:string;icon?:any}){return <div className="empty">{icon}<span>{text}</span></div>}
