import { FormEvent,useEffect,useState } from "react";
import { Download,KeyRound,RefreshCw,RotateCcw,Save,Trash2 } from "lucide-react";
import { Layout } from "../components/Layout";
import { api,downloadFile } from "../lib/api";
import { isAdmin,useCurrentUser } from "../lib/permissions";

const platforms:any={cisco_ios:"Cisco IOS",eos:"Arista EOS",junos:"Juniper Junos",fortios:"FortiOS (sauvegarde seule)"};

export function NetworkConfigurations(){
  const user=useCurrentUser(),admin=isAdmin(user),[credentials,setCredentials]=useState<any[]>([]),[assets,setAssets]=useState<any[]>([]),[versions,setVersions]=useState<any[]>([]),[restores,setRestores]=useState<any[]>([]),[message,setMessage]=useState(""),[rotateId,setRotateId]=useState("");
  const load=async()=>{try{const [allCredentials,allAssets,allVersions]=await Promise.all([api<any[]>("/credentials"),api<any[]>("/assets"),api<any[]>("/device-configurations")]);setCredentials(allCredentials.filter(x=>x.kind==="ssh"));setAssets(allAssets);setVersions(allVersions);if(admin)setRestores(await api<any[]>("/device-configuration-restores"));}catch(x:any){setMessage(x.message)}};
  useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[admin]);
  async function saveCredential(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),privateKey=String(f.get("private_key")||"").trim();const payload:any={name:f.get("name"),username:f.get("username"),password:privateKey?null:f.get("password"),private_key:privateKey||null,passphrase:f.get("passphrase")||null,host_key:f.get("host_key"),port:Number(f.get("port")),description:f.get("description")||null,site_id:null};try{await api(rotateId?`/credentials/${rotateId}/rotate`:"/credentials/ssh",{method:rotateId?"PATCH":"POST",body:JSON.stringify(payload)});setMessage(rotateId?"Identifiant renouvelé.":"Identifiant SSH ajouté.");setRotateId("");form.reset();load()}catch(x:any){setMessage(x.message)}}
  async function removeCredential(id:string){if(!confirm("Supprimer cet identifiant SSH ?"))return;try{await api(`/credentials/${id}`,{method:"DELETE"});load()}catch(x:any){setMessage(x.message)}}
  async function backup(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api("/device-configurations",{method:"POST",body:JSON.stringify({asset_id:f.get("asset_id"),credential_id:f.get("credential_id"),platform:f.get("platform")})});setMessage("Sauvegarde mise en file d’attente.");load()}catch(x:any){setMessage(x.message)}}
  async function restore(row:any){const confirmation=prompt(`Opération sensible. Saisissez RESTORE suivi du nom ou de l’adresse exacte de l’équipement.\nExemple : RESTORE ${row.asset_name||"192.0.2.1"}`);if(!confirmation)return;try{await api(`/device-configurations/${row.id}/restore`,{method:"POST",body:JSON.stringify({confirmation})});setMessage("Restauration mise en file d’attente. Une sauvegarde de secours sera créée avant toute modification.");load()}catch(x:any){setMessage(x.message)}}
  return <Layout title="Configurations réseau">
    {message&&<div className="hint">{message}</div>}
    <div className="split">
      {admin&&<article className="panel formPanel"><h3><KeyRound/> {rotateId?"Renouveler l’identifiant":"Coffre SSH"}</h3><p className="muted">Les secrets sont chiffrés et ne sont jamais réaffichés. La clé hôte épinglée protège contre l’interception SSH.</p><form onSubmit={saveCredential}><label>Nom<input name="name" required defaultValue={credentials.find(x=>x.id===rotateId)?.name||""}/></label><label>Utilisateur<input name="username" required autoComplete="off"/></label><label>Mot de passe<input name="password" type="password" autoComplete="new-password"/></label><label>Ou clé privée<textarea name="private_key" rows={4} placeholder="-----BEGIN OPENSSH PRIVATE KEY-----"/></label><label>Phrase secrète de la clé<input name="passphrase" type="password" autoComplete="new-password"/></label><label>Clé publique hôte OpenSSH<textarea name="host_key" rows={3} required placeholder="ssh-ed25519 AAAA…"/></label><label>Port<input name="port" type="number" min="1" max="65535" defaultValue="22" required/></label><label>Description<input name="description"/></label><div className="rowActions"><button className="primary"><Save/> {rotateId?"Renouveler":"Enregistrer"}</button>{rotateId&&<button type="button" onClick={()=>setRotateId("")}>Annuler</button>}</div></form></article>}
      <article className="panel formPanel"><h3><Save/> Nouvelle sauvegarde</h3><form onSubmit={backup}><label>Équipement<select name="asset_id" required><option value="">Choisir…</option>{assets.map(x=><option key={x.id} value={x.id}>{x.hostname||x.addresses?.[0]?.address||x.id}</option>)}</select></label><label>Identifiant SSH<select name="credential_id" required><option value="">Choisir…</option>{credentials.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Plateforme<select name="platform" required>{Object.entries(platforms).map(([value,label]:any)=><option key={value} value={value}>{label}</option>)}</select></label><button className="primary"><Save/> Sauvegarder maintenant</button></form><div className="scanList" style={{marginTop:16}}>{credentials.map(row=><div key={row.id}><KeyRound/><span><b>{row.name}</b><small>{row.description||"SSH"}{row.last_used_at?` · utilisé ${new Date(row.last_used_at).toLocaleString("fr")}`:" · jamais utilisé"}</small></span>{admin&&<><button className="icon" title="Renouveler" onClick={()=>setRotateId(row.id)}><RefreshCw/></button><button className="icon danger" title="Supprimer" onClick={()=>removeCredential(row.id)}><Trash2/></button></>}</div>)}</div></article>
    </div>
    <article className="panel" style={{marginTop:12}}><h3>Versions chiffrées</h3><div className="scanList">{versions.length===0&&<p>Aucune sauvegarde.</p>}{versions.map(row=><div key={row.id}><Save/><span><b>{row.asset_name||row.asset_id} · {platforms[row.platform]||row.platform}</b><small>{new Date(row.created_at).toLocaleString("fr")}{row.byte_count?` · ${Math.ceil(row.byte_count/1024)} Kio`:""}{row.checksum?` · SHA-256 ${row.checksum.slice(0,12)}…`:""}{row.error?` · ${row.error}`:""}</small></span><em className={`badge ${row.status}`}>{row.status}</em>{admin&&row.status==="completed"&&<><button className="icon" title="Télécharger" onClick={()=>downloadFile(`/device-configurations/${row.id}/download`,`netscope-${row.asset_name||row.asset_id}.cfg`).catch(x=>setMessage(x.message))}><Download/></button>{platforms[row.platform]!==platforms.fortios&&<button className="icon danger" title="Restaurer" onClick={()=>restore(row)}><RotateCcw/></button>}</>}</div>)}</div></article>
    {admin&&restores.length>0&&<article className="panel" style={{marginTop:12}}><h3>Journal des restaurations</h3><div className="scanList">{restores.map(row=><div key={row.id}><RotateCcw/><span><b>{row.configuration_id}</b><small>{new Date(row.created_at).toLocaleString("fr")}{row.pre_backup_id?` · secours ${row.pre_backup_id}`:""}{row.error?` · ${row.error}`:""}</small></span><em className={`badge ${row.status}`}>{row.status}</em></div>)}</div></article>}
  </Layout>
}
