import { FormEvent,useEffect,useState } from "react";
import { Radio,Route,ShieldAlert,Trash2 } from "lucide-react";
import { Layout } from "../components/Layout";
import { api,Asset } from "../lib/api";
import { canOperate,isAdmin,useCurrentUser } from "../lib/permissions";
export function NetworkIntelligence(){
 const user=useCurrentUser(),editable=canOperate(user),administrative=isAdmin(user);const [routes,setRoutes]=useState<any[]>([]),[radios,setRadios]=useState<any[]>([]),[assets,setAssets]=useState<Asset[]>([]),[tab,setTab]=useState("routes"),[search,setSearch]=useState(""),[message,setMessage]=useState("");
 const load=()=>{api<any[]>("/routes").then(setRoutes).catch(x=>setMessage(x.message));api<any[]>("/wireless").then(setRadios).catch(x=>setMessage(x.message));api<Asset[]>("/assets").then(setAssets)};useEffect(load,[]);
 async function wireless(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{await api("/wireless/observations",{method:"POST",body:JSON.stringify({asset_id:f.get("asset_id"),radio_name:f.get("radio_name"),band:f.get("band")||null,channel:f.get("channel")?Number(f.get("channel")):null,channel_width_mhz:f.get("channel_width_mhz")?Number(f.get("channel_width_mhz")):null,utilization:f.get("utilization")?Number(f.get("utilization")):null,radio_client_count:Number(f.get("radio_client_count")||0),ssid:f.get("ssid"),bssid:f.get("bssid"),security:f.get("security")||null,vlan_id:f.get("vlan_id")?Number(f.get("vlan_id")):null,hidden:false,client_count:Number(f.get("client_count")||0)})});form.reset();setMessage("Observation Wi-Fi enregistrée");load()}catch(x:any){setMessage(x.message)}}
 async function removeNetwork(id:string){if(!confirm("Supprimer cette observation BSSID ?"))return;try{await api(`/wireless/networks/${id}`,{method:"DELETE"});load()}catch(x:any){setMessage(x.message)}}
 const filtered=routes.filter(r=>`${r.prefix} ${r.next_hop||""} ${r.protocol} ${r.device_name||""}`.toLowerCase().includes(search.toLowerCase()));const secure=(value:string|null)=>{const normalized=(value||"").toUpperCase();return normalized.startsWith("WPA2")||normalized.startsWith("WPA3")};
 return <Layout title="Routage et Wi-Fi"><div className="tabs"><button className={tab==="routes"?"active":""} onClick={()=>setTab("routes")}><Route/> Routage</button><button className={tab==="wireless"?"active":""} onClick={()=>setTab("wireless")}><Radio/> Wi-Fi</button></div>{message&&<div className="hint">{message}</div>}
 {tab==="routes"&&<article className="panel tablePanel"><div className="pageHead"><h3>Tables de routage collectées</h3><input placeholder="Préfixe, next-hop, protocole…" value={search} onChange={e=>setSearch(e.target.value)}/></div><table><thead><tr><th>Équipement</th><th>Préfixe</th><th>IP</th><th>Next-hop</th><th>Interface</th><th>Protocole</th><th>Métrique</th><th>État</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.device_name||r.network_device_id}</td><td className="mono">{r.prefix}</td><td>IPv{r.version}</td><td className="mono">{r.next_hop||"direct"}</td><td>{r.if_index||"—"}</td><td>{r.protocol}</td><td>{r.metric??"—"}</td><td><span className={`badge ${r.active?"completed":"failed"}`}>{r.active?"active":"retirée"}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">Aucune route collectée</div>}</article>}
 {tab==="wireless"&&<><div className="metrics"><article className="metric"><div><span>Radios</span><strong>{radios.length}</strong></div><i className="blue"><Radio/></i></article><article className="metric"><div><span>SSID / BSSID</span><strong>{radios.reduce((n,r)=>n+r.networks.length,0)}</strong></div><i className="green"><Radio/></i></article><article className="metric"><div><span>Réseaux faibles</span><strong>{radios.flatMap(r=>r.networks).filter((n:any)=>!secure(n.security)).length}</strong></div><i className="red"><ShieldAlert/></i></article></div><div className="split">{editable&&<article className="panel formPanel"><h3>Enregistrer une observation contrôleur</h3><form onSubmit={wireless}><label>Point d’accès<select name="asset_id" required>{assets.map(a=><option key={a.id} value={a.id}>{a.hostname||a.addresses[0]?.address||a.id}</option>)}</select></label><label>Radio<input name="radio_name" placeholder="radio0" required/></label><label>Bande<select name="band"><option value="">Inconnue</option><option>2.4 GHz</option><option>5 GHz</option><option>6 GHz</option></select></label><label>Canal<input name="channel" type="number" min="1" max="233"/></label><label>Largeur MHz<input name="channel_width_mhz" type="number" min="5" max="320"/></label><label>Utilisation %<input name="utilization" type="number" min="0" max="100" step="0.1"/></label><label>Clients radio<input name="radio_client_count" type="number" min="0" defaultValue="0"/></label><label>SSID<input name="ssid" required/></label><label>BSSID<input name="bssid" placeholder="00:11:22:33:44:55" required/></label><label>Sécurité<select name="security"><option>WPA3</option><option>WPA2/WPA3</option><option>WPA2</option><option>WPA</option><option>WEP</option><option>OPEN</option></select></label><label>VLAN<input name="vlan_id" type="number" min="1" max="4094"/></label><label>Clients SSID<input name="client_count" type="number" min="0" defaultValue="0"/></label><button className="primary">Enregistrer</button></form></article>}<article className="panel tablePanel"><table><thead><tr><th>Point d’accès / radio</th><th>Bande</th><th>Canal</th><th>Utilisation</th><th>SSID</th><th>Sécurité</th><th>Clients</th>{administrative&&<th>Actions</th>}</tr></thead><tbody>{radios.flatMap(r=>r.networks.map((n:any)=><tr key={n.id}><td>{r.asset_name||r.asset_id} · {r.radio_name}</td><td>{r.band||"—"}</td><td>{r.channel||"—"}</td><td>{r.utilization==null?"—":`${r.utilization}%`}</td><td>{n.hidden?"SSID masqué":n.ssid}<small className="mono"> {n.bssid}</small></td><td>{n.security||"OPEN"}</td><td>{n.client_count}</td>{administrative&&<td><button className="icon danger" onClick={()=>removeNetwork(n.id)}><Trash2/></button></td>}</tr>))}</tbody></table></article></div></>}
 </Layout>}
