import { FormEvent,useEffect,useState } from "react";
import { Copy,KeyRound,RadioTower,Trash2 } from "lucide-react";
import { Layout } from "../components/Layout";
import { api } from "../lib/api";
export function Probes(){
 const [rows,setRows]=useState<any[]>([]),[sites,setSites]=useState<any[]>([]),[vrfs,setVrfs]=useState<any[]>([]),[token,setToken]=useState(""),[message,setMessage]=useState("");
 const load=()=>{api<any[]>("/probes").then(setRows).catch(x=>setMessage(x.message));api<any[]>("/sites").then(setSites);api<any[]>("/ipam/vrfs").then(setVrfs);};useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{const result:any=await api("/probes",{method:"POST",body:JSON.stringify({name:f.get("name"),site_id:f.get("site_id")||null,vrf_id:f.get("vrf_id")||null})});setToken(result.token);setMessage(result.warning);form.reset();load()}catch(x:any){setMessage(x.message)}}
 async function rotate(id:string){if(!confirm("Révoquer l'ancien jeton ?"))return;const result:any=await api(`/probes/${id}/rotate-token`,{method:"POST"});setToken(result.token);setMessage(result.warning)}
 async function toggle(row:any){await api(`/probes/${row.id}?enabled=${!row.enabled}`,{method:"PATCH"});load()}
 async function remove(id:string){if(!confirm("Supprimer cette sonde ?"))return;try{await api(`/probes/${id}`,{method:"DELETE"});load()}catch(x:any){setMessage(x.message)}}
 return <Layout title="Sondes distribuées">{message&&<div className="hint">{message}</div>}{token&&<article className="panel"><h3>Jeton affiché une seule fois</h3><div className="rowActions"><code style={{overflowWrap:"anywhere"}}>{token}</code><button onClick={()=>navigator.clipboard.writeText(token)}><Copy/> Copier</button></div></article>}<div className="split" style={{marginTop:12}}><article className="panel formPanel"><h3><RadioTower/> Nouvelle sonde</h3><form onSubmit={create}><label>Nom<input name="name" required/></label><label>Site<select name="site_id"><option value="">Aucun</option>{sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>VRF<select name="vrf_id"><option value="">Globale</option>{vrfs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="primary">Créer</button></form></article><article className="panel"><h3>État des sondes</h3><div className="scanList">{rows.map(row=><div key={row.id}><RadioTower/><span><b>{row.name}</b><small>{row.version||"jamais connectée"} · {(row.capabilities||[]).join(", ")||"aucune capacité"} · {row.last_seen_at?new Date(row.last_seen_at).toLocaleString("fr"):"aucun heartbeat"}</small></span><em className={`badge ${row.online?"completed":"failed"}`}>{row.online?"en ligne":row.enabled?"hors ligne":"désactivée"}</em><button className="icon" onClick={()=>toggle(row)}><RadioTower/></button><button className="icon" onClick={()=>rotate(row.id)}><KeyRound/></button><button className="icon danger" onClick={()=>remove(row.id)}><Trash2/></button></div>)}</div></article></div></Layout>
}
