import { FormEvent,useEffect,useState } from "react";
import { Copy,KeyRound,Play,RadioTower,RefreshCw,Trash2 } from "lucide-react";
import { Layout } from "../components/Layout";
import { api } from "../lib/api";

export function Probes(){
 const [rows,setRows]=useState<any[]>([]),[sites,setSites]=useState<any[]>([]),[vrfs,setVrfs]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[selected,setSelected]=useState(""),[live,setLive]=useState<any>(),[token,setToken]=useState(""),[message,setMessage]=useState("");
 const load=()=>{api<any[]>("/probes").then(data=>{setRows(data);setSelected(value=>value||data[0]?.id||"")}).catch(x=>setMessage(x.message));api<any[]>("/sites").then(setSites);api<any[]>("/ipam/vrfs").then(setVrfs);api<any[]>("/scan-profiles").then(data=>setProfiles(data.filter(p=>(p.modules||[]).every((m:string)=>["icmp","arp","nmap","dns"].includes(m)))))};
 const loadLive=()=>selected&&api<any>(`/probes/${selected}/live`).then(setLive).catch((x:any)=>setMessage(x.message));
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{setLive(undefined);loadLive();const timer=setInterval(loadLive,3000);return()=>clearInterval(timer)},[selected]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);try{const result:any=await api("/probes",{method:"POST",body:JSON.stringify({name:f.get("name"),site_id:f.get("site_id")||null,vrf_id:f.get("vrf_id")||null})});setToken(result.token);setMessage(result.warning);form.reset();load()}catch(x:any){setMessage(x.message)}}
 async function discover(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),probe=rows.find(x=>x.id===selected);try{await api("/scans",{method:"POST",body:JSON.stringify({target:f.get("target"),profile_id:f.get("profile_id"),probe_id:selected,vrf_id:probe?.vrf_id||null})});setMessage("Découverte envoyée à la sonde.");loadLive()}catch(x:any){setMessage(x.message)}}
 async function rotate(id:string){if(!confirm("Révoquer l'ancien jeton ?"))return;const result:any=await api(`/probes/${id}/rotate-token`,{method:"POST"});setToken(result.token);setMessage(result.warning)}
 async function toggle(row:any){await api(`/probes/${row.id}?enabled=${!row.enabled}`,{method:"PATCH"});load()}
 async function remove(id:string){if(!confirm("Supprimer cette sonde ?"))return;try{await api(`/probes/${id}`,{method:"DELETE"});if(selected===id)setSelected("");load()}catch(x:any){setMessage(x.message)}}
 const probe=rows.find(x=>x.id===selected),networks=live?.reachable_networks||probe?.reachable_networks||[];
 return <Layout title="Sondes et découverte live">
  {message&&<div className="hint">{message}</div>}
  {token&&<article className="panel"><h3>Jeton affiché une seule fois</h3><div className="rowActions"><code style={{overflowWrap:"anywhere"}}>{token}</code><button onClick={()=>navigator.clipboard.writeText(token)}><Copy/> Copier</button></div></article>}
  <div className="split" style={{marginTop:12}}>
   <article className="panel formPanel"><h3><RadioTower/> Nouvelle sonde</h3><form onSubmit={create}><label>Nom<input name="name" required/></label><label>Site<select name="site_id"><option value="">Aucun</option>{sites.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>VRF<select name="vrf_id"><option value="">Globale</option>{vrfs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="primary">Créer</button></form></article>
   <article className="panel"><h3>État des sondes</h3><div className="scanList">{rows.map(row=><div key={row.id} onClick={()=>setSelected(row.id)} style={{cursor:"pointer",outline:selected===row.id?"2px solid #38bdf8":"none"}}><RadioTower/><span><b>{row.name}</b><small>{row.last_ip||"IP inconnue"} · {row.version||"jamais connectée"} · {row.last_seen_at?new Date(row.last_seen_at).toLocaleString("fr"):"aucun heartbeat"}</small></span><em className={`badge ${row.online?"completed":"failed"}`}>{row.online?"en ligne":row.enabled?"hors ligne":"désactivée"}</em><button className="icon" title="Activer/désactiver" onClick={e=>{e.stopPropagation();toggle(row)}}><RadioTower/></button><button className="icon" title="Renouveler le jeton" onClick={e=>{e.stopPropagation();rotate(row.id)}}><KeyRound/></button><button className="icon danger" title="Supprimer" onClick={e=>{e.stopPropagation();remove(row.id)}}><Trash2/></button></div>)}</div></article>
  </div>
  {probe&&<div className="split" style={{marginTop:12}}>
   <article className="panel formPanel"><h3><Play/> Forcer une détection</h3><p className="hint">Le scan est exécuté depuis <b>{probe.name}</b>. Les résultats apparaissent à droite sans recharger la page.</p><form onSubmit={discover}><label>Réseau cible<input name="target" list="probe-networks" placeholder="192.168.1.0/24" required/><datalist id="probe-networks">{networks.map((n:string)=><option value={n} key={n}/>)}</datalist></label><label>Profil<select name="profile_id" required>{profiles.map(x=><option value={x.id} key={x.id}>{x.name} · {(x.modules||[]).join(", ")}</option>)}</select></label><button className="primary" disabled={!probe.online||!profiles.length}><Play/> Détecter maintenant</button></form><h3>Réseaux accessibles annoncés</h3>{networks.length?<div className="rowActions" style={{flexWrap:"wrap"}}>{networks.map((n:string)=><button key={n} onClick={()=>{const input=document.querySelector<HTMLInputElement>('input[name="target"]');if(input)input.value=n}}>{n}</button>)}</div>:<p className="readOnlyNotice">La sonde doit être mise à jour en version 1.1 et envoyer un heartbeat.</p>}</article>
   <article className="panel"><div className="rowActions"><h3>Équipements détectés</h3><button className="icon" title="Actualiser" onClick={loadLive}><RefreshCw/></button></div><div className="scanList">{(live?.assets||[]).map((asset:any)=><div key={`${asset.ip_address}-${asset.asset_id||asset.mac_address}`}><RadioTower/><span><b>{asset.hostname||asset.ip_address}</b><small>{asset.hostname&&`${asset.ip_address} · `}{asset.manufacturer||"constructeur inconnu"} · {asset.device_type||asset.source} · {new Date(asset.observed_at).toLocaleTimeString("fr")}</small></span>{asset.asset_id&&<a href={`#/assets/${asset.asset_id}`}>Voir</a>}</div>)}{live&&!live.assets.length&&<p className="readOnlyNotice">Aucun équipement détecté par cette sonde.</p>}</div><h3>Activité en direct</h3><div className="scanList">{(live?.scans||[]).slice(0,8).map((scan:any)=><div key={scan.id}><RefreshCw/><span><b>{scan.target}</b><small>{scan.result_count||0} résultat(s){scan.error&&` · ${scan.error}`}</small></span><em className={`badge ${scan.status}`}>{scan.status}</em></div>)}</div></article>
  </div>}
 </Layout>
}
